#-------------------------------
# General Site Settings
title: ITSEC
logo: # You can add own logo. For example '/images/logo.png'.
description: 
baseurl: "" # The subpath of your site, e.g. /blog
url: "ctf.itsec.ac.id" # The base hostname & protocol for your site, e.g. http://example.com


#-------------------------------
# Author Settings
author:
  name: Sarah Exploit
  avatar: '/images/jeje3.jpeg'


#-------------------------------
# Hero Settings
hero:
  title: Sarah Exploit
  description: DevOps, Cybersecurity, Digital Forensic
  image: '/images/01.jpg'


#-------------------------------
# Contact Settings
contact:
  email: sarah@itsec.ac.id # Add your email for contact form
  description:  # Add a description of your form

# NOTE
# Norlin theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.


#-------------------------------
# Footer section
# Example of adding a new link to the footer - {icon: "ion-logo-github", link: "https://github.com"}
# Other icons can be found at https://ionicons.com/v4/
social:
- {icon: "ion-logo-twitter", link: "https://twitter.com/IDsec_"}
- {icon: "ion-logo-linkedin", link: "https://www.linkedin.com/in/"}
- {icon: "ion-logo-instagram", link: "https://www.instagram.com/enoleriand"}
- {icon: "ion-logo-facebook", link: "https://www.facebook.com/SarahExploit"}
- {icon: "ion-logo-bug", link: "https://www.bugcrowd.com/"}}


#-------------------------------
# Comment (Disqus)
disqus-identifier: darksec

# Google Analytics
google-analytics: 


mailchimp: enable 
mailchimp-identifier: 

# settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
  parse_block_html: true

collections:
  tabs:
    output: true
    sort_by: order

paginate: 7
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: ''
      type: posts
    values:
      layout: post
      autoads: true
      toc: true
      permalink: /:title/

# defaults:
 # -
 #   scope:
 #     path: ''          
 #     type: posts
 #   values:
 #     layout: post
 #     comments: true    
 #     toc: true         
 #     autoads: true     
 #     permalink: /:title/
 # -
 #   scope:
 #     path: _drafts
 #   values:
 #     comments: false 

include:
  - _pages

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  /tags/:name/

sass:
  sass_dir: _sass
  style: compressed
  
compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]
